os: linux
dist: focal
branches:
  only:
    - dev
    - feature

cache:
  directories:
    - $HOME/.cache/pip

jobs:
  include:
    - stage: test
      name: Run Python Tests
      language: python
      python:
        - "3.12"
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y git autoconf libssl-dev libxml2-dev libxslt1-dev libjpeg-dev libffi-dev libudev-dev zlib1g-dev pkg-config libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libswresample-dev libavfilter-dev ffmpeg libgammu-dev
      install:
        - pip install --upgrade pip
        - pip install -r requirements_all.txt
        - pip install -r requirements_test_all.txt
      script:
        - ./script/setup
        - pytest ./tests/components/remember_the_milk/ --cov=homeassistant.components.remember_the_milk --cov-report xml:coverage.xml --cov-fail-under=50 -rw -vv

    - stage: sonar
      name: SonarCloud Analysis
      language: java
      jdk:
        - openjdk17
      addons:
        sonarcloud:
          organization: "amalte"
      before_install:
        - java -version # Verify Java version
      install: skip
      needs: test
      script:
        - sonar-scanner
