# Project identification
sonar.organization=amalte  

# Paths to source code
sonar.sources=homeassistant/components/remember_the_milk

# Exclude other components and tests
sonar.exclusions=homeassistant/components/**, **/tests/**

# Include only the remember_the_milk component
sonar.inclusions=homeassistant/components/remember_the_milk/**

# Encoding of the source files
sonar.sourceEncoding=UTF-8

